"""Configuration constants for stratum2 — Sapiens2 model IDs, artifact filenames.

SAPIENS2_SIZE controls which model variant is used across all tasks.
Set via SAPIENS2_SIZE env var (default: '5b').
"""

from __future__ import annotations

import os
from pathlib import Path

# --- Model size (single parameter for all tasks) ---
SAPIENS2_SIZE = os.environ.get("SAPIENS2_SIZE", "5b")

# --- HF repos for task checkpoints ---
SAPIENS2_REPOS = {
    "seg": f"facebook/sapiens2-seg-{SAPIENS2_SIZE}",
    "normal": f"facebook/sapiens2-normal-{SAPIENS2_SIZE}",
    "pointmap": f"facebook/sapiens2-pointmap-{SAPIENS2_SIZE}",
    "pose": f"facebook/sapiens2-pose-{SAPIENS2_SIZE}",
    "matting": "facebook/sapiens2-matting-1b",  # Only 1B available for matting
}

# --- Checkpoint filenames ---
SAPIENS2_FILENAMES = {
    "seg": f"sapiens2_{SAPIENS2_SIZE}_seg.safetensors",
    "normal": f"sapiens2_{SAPIENS2_SIZE}_normal.safetensors",
    "pointmap": f"sapiens2_{SAPIENS2_SIZE}_pointmap.safetensors",
    "pose": f"sapiens2_{SAPIENS2_SIZE}_pose.safetensors",
    "matting": "sapiens2_1b_matting.safetensors",
}

# --- Cache directory for downloaded checkpoints ---
SAPIENS2_CACHE_DIR = Path(
    os.environ.get("SAPIENS2_CACHE_DIR", "/mnt/nas-ai-models/sapiens2")
)

# --- Person detector for pose ---
POSE_DETECTOR_REPO = "facebook/detr-resnet-101-dc5"

# --- New artifact filenames (stratum2-specific) ---
SEG2_FILE = "seg2.npy"
NORMAL2_FILE = "normal2.npy"
POINTMAP_FILE = "pointmap.npy"
POSE2_FILE = "pose2.npy"
MATTING_FILE = "matting.npy"
DETERMINATIONS_FILE = "determinations.json"
CAPTION2_FILE = "caption2.txt"
T52_HIDDEN_FILE = "t52_hidden.npy"
T52_MASK_FILE = "t52_mask.npy"

# --- Frozen Index Tables ---

DOME_29 = [
    "Background",
    "Apparel",
    "Eyeglass",
    "Face_Neck",
    "Hair",
    "Left_Foot",
    "Left_Hand",
    "Left_Lower_Arm",
    "Left_Lower_Leg",
    "Left_Shoe",
    "Left_Sock",
    "Left_Upper_Arm",
    "Left_Upper_Leg",
    "Lower_Clothing",
    "Right_Foot",
    "Right_Hand",
    "Right_Lower_Arm",
    "Right_Lower_Leg",
    "Right_Shoe",
    "Right_Sock",
    "Right_Upper_Arm",
    "Right_Upper_Leg",
    "Torso",
    "Upper_Clothing",
    "Lower_Lip",
    "Upper_Lip",
    "Lower_Teeth",
    "Upper_Teeth",
    "Tongue",
]

GOLIATH_308 = [
    "nose",
    "left_eye",
    "right_eye",
    "left_ear",
    "right_ear",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
    "left_big_toe",
    "left_small_toe",
    "left_heel",
    "right_big_toe",
    "right_small_toe",
    "right_heel",
    "right_thumb4",
    "right_thumb3",
    "right_thumb2",
    "right_thumb_third_joint",
    "right_forefinger4",
    "right_forefinger3",
    "right_forefinger2",
    "right_forefinger_third_joint",
    "right_middle_finger4",
    "right_middle_finger3",
    "right_middle_finger2",
    "right_middle_finger_third_joint",
    "right_ring_finger4",
    "right_ring_finger3",
    "right_ring_finger2",
    "right_ring_finger_third_joint",
    "right_pinky_finger4",
    "right_pinky_finger3",
    "right_pinky_finger2",
    "right_pinky_finger_third_joint",
    "right_wrist",
    "left_thumb4",
    "left_thumb3",
    "left_thumb2",
    "left_thumb_third_joint",
    "left_forefinger4",
    "left_forefinger3",
    "left_forefinger2",
    "left_forefinger_third_joint",
    "left_middle_finger4",
    "left_middle_finger3",
    "left_middle_finger2",
    "left_middle_finger_third_joint",
    "left_ring_finger4",
    "left_ring_finger3",
    "left_ring_finger2",
    "left_ring_finger_third_joint",
    "left_pinky_finger4",
    "left_pinky_finger3",
    "left_pinky_finger2",
    "left_pinky_finger_third_joint",
    "left_wrist",
    "left_olecranon",
    "right_olecranon",
    "left_cubital_fossa",
    "right_cubital_fossa",
    "left_acromion",
    "right_acromion",
    "neck",
    "center_of_glabella",
    "center_of_nose_root",
    "tip_of_nose_bridge",
    "midpoint_1_of_nose_bridge",
    "midpoint_2_of_nose_bridge",
    "midpoint_3_of_nose_bridge",
    "center_of_labiomental_groove",
    "tip_of_chin",
    "upper_startpoint_of_r_eyebrow",
    "lower_startpoint_of_r_eyebrow",
    "end_of_r_eyebrow",
    "upper_midpoint_1_of_r_eyebrow",
    "lower_midpoint_1_of_r_eyebrow",
    "upper_midpoint_2_of_r_eyebrow",
    "upper_midpoint_3_of_r_eyebrow",
    "lower_midpoint_2_of_r_eyebrow",
    "lower_midpoint_3_of_r_eyebrow",
    "upper_startpoint_of_l_eyebrow",
    "lower_startpoint_of_l_eyebrow",
    "end_of_l_eyebrow",
    "upper_midpoint_1_of_l_eyebrow",
    "lower_midpoint_1_of_l_eyebrow",
    "upper_midpoint_2_of_l_eyebrow",
    "upper_midpoint_3_of_l_eyebrow",
    "lower_midpoint_2_of_l_eyebrow",
    "lower_midpoint_3_of_l_eyebrow",
    "l_inner_end_of_upper_lash_line",
    "l_outer_end_of_upper_lash_line",
    "l_centerpoint_of_upper_lash_line",
    "l_midpoint_2_of_upper_lash_line",
    "l_midpoint_1_of_upper_lash_line",
    "l_midpoint_6_of_upper_lash_line",
    "l_midpoint_5_of_upper_lash_line",
    "l_midpoint_4_of_upper_lash_line",
    "l_midpoint_3_of_upper_lash_line",
    "l_outer_end_of_upper_eyelid_line",
    "l_midpoint_6_of_upper_eyelid_line",
    "l_midpoint_2_of_upper_eyelid_line",
    "l_midpoint_5_of_upper_eyelid_line",
    "l_centerpoint_of_upper_eyelid_line",
    "l_midpoint_4_of_upper_eyelid_line",
    "l_midpoint_1_of_upper_eyelid_line",
    "l_midpoint_3_of_upper_eyelid_line",
    "l_midpoint_6_of_upper_crease_line",
    "l_midpoint_2_of_upper_crease_line",
    "l_midpoint_5_of_upper_crease_line",
    "l_centerpoint_of_upper_crease_line",
    "l_midpoint_4_of_upper_crease_line",
    "l_midpoint_1_of_upper_crease_line",
    "l_midpoint_3_of_upper_crease_line",
    "r_inner_end_of_upper_lash_line",
    "r_outer_end_of_upper_lash_line",
    "r_centerpoint_of_upper_lash_line",
    "r_midpoint_1_of_upper_lash_line",
    "r_midpoint_2_of_upper_lash_line",
    "r_midpoint_3_of_upper_lash_line",
    "r_midpoint_4_of_upper_lash_line",
    "r_midpoint_5_of_upper_lash_line",
    "r_midpoint_6_of_upper_lash_line",
    "r_outer_end_of_upper_eyelid_line",
    "r_midpoint_3_of_upper_eyelid_line",
    "r_midpoint_1_of_upper_eyelid_line",
    "r_midpoint_4_of_upper_eyelid_line",
    "r_centerpoint_of_upper_eyelid_line",
    "r_midpoint_5_of_upper_eyelid_line",
    "r_midpoint_2_of_upper_eyelid_line",
    "r_midpoint_6_of_upper_eyelid_line",
    "r_midpoint_3_of_upper_crease_line",
    "r_midpoint_1_of_upper_crease_line",
    "r_midpoint_4_of_upper_crease_line",
    "r_centerpoint_of_upper_crease_line",
    "r_midpoint_5_of_upper_crease_line",
    "r_midpoint_2_of_upper_crease_line",
    "r_midpoint_6_of_upper_crease_line",
    "l_inner_end_of_lower_lash_line",
    "l_outer_end_of_lower_lash_line",
    "l_centerpoint_of_lower_lash_line",
    "l_midpoint_2_of_lower_lash_line",
    "l_midpoint_1_of_lower_lash_line",
    "l_midpoint_6_of_lower_lash_line",
    "l_midpoint_5_of_lower_lash_line",
    "l_midpoint_4_of_lower_lash_line",
    "l_midpoint_3_of_lower_lash_line",
    "l_outer_end_of_lower_eyelid_line",
    "l_midpoint_6_of_lower_eyelid_line",
    "l_midpoint_2_of_lower_eyelid_line",
    "l_midpoint_5_of_lower_eyelid_line",
    "l_centerpoint_of_lower_eyelid_line",
    "l_midpoint_4_of_lower_eyelid_line",
    "l_midpoint_1_of_lower_eyelid_line",
    "l_midpoint_3_of_lower_eyelid_line",
    "r_inner_end_of_lower_lash_line",
    "r_outer_end_of_lower_lash_line",
    "r_centerpoint_of_lower_lash_line",
    "r_midpoint_1_of_lower_lash_line",
    "r_midpoint_2_of_lower_lash_line",
    "r_midpoint_3_of_lower_lash_line",
    "r_midpoint_4_of_lower_lash_line",
    "r_midpoint_5_of_lower_lash_line",
    "r_midpoint_6_of_lower_lash_line",
    "r_outer_end_of_lower_eyelid_line",
    "r_midpoint_3_of_lower_eyelid_line",
    "r_midpoint_1_of_lower_eyelid_line",
    "r_midpoint_4_of_lower_eyelid_line",
    "r_centerpoint_of_lower_eyelid_line",
    "r_midpoint_5_of_lower_eyelid_line",
    "r_midpoint_2_of_lower_eyelid_line",
    "r_midpoint_6_of_lower_eyelid_line",
    "tip_of_nose",
    "bottom_center_of_nose",
    "r_outer_corner_of_nose",
    "l_outer_corner_of_nose",
    "inner_corner_of_r_nostril",
    "outer_corner_of_r_nostril",
    "upper_corner_of_r_nostril",
    "inner_corner_of_l_nostril",
    "outer_corner_of_l_nostril",
    "upper_corner_of_l_nostril",
    "r_outer_corner_of_mouth",
    "l_outer_corner_of_mouth",
    "center_of_cupid_bow",
    "center_of_lower_outer_lip",
    "midpoint_1_of_upper_outer_lip",
    "midpoint_2_of_upper_outer_lip",
    "midpoint_1_of_lower_outer_lip",
    "midpoint_2_of_lower_outer_lip",
    "midpoint_3_of_upper_outer_lip",
    "midpoint_4_of_upper_outer_lip",
    "midpoint_5_of_upper_outer_lip",
    "midpoint_6_of_upper_outer_lip",
    "midpoint_3_of_lower_outer_lip",
    "midpoint_4_of_lower_outer_lip",
    "midpoint_5_of_lower_outer_lip",
    "midpoint_6_of_lower_outer_lip",
    "r_inner_corner_of_mouth",
    "l_inner_corner_of_mouth",
    "center_of_upper_inner_lip",
    "center_of_lower_inner_lip",
    "midpoint_1_of_upper_inner_lip",
    "midpoint_2_of_upper_inner_lip",
    "midpoint_1_of_lower_inner_lip",
    "midpoint_2_of_lower_inner_lip",
    "midpoint_3_of_upper_inner_lip",
    "midpoint_4_of_upper_inner_lip",
    "midpoint_5_of_upper_inner_lip",
    "midpoint_6_of_upper_inner_lip",
    "midpoint_3_of_lower_inner_lip",
    "midpoint_4_of_lower_inner_lip",
    "midpoint_5_of_lower_inner_lip",
    "midpoint_6_of_lower_inner_lip",
    "l_top_end_of_inferior_crus",
    "l_top_end_of_superior_crus",
    "l_start_of_antihelix",
    "l_end_of_antihelix",
    "l_midpoint_1_of_antihelix",
    "l_midpoint_1_of_inferior_crus",
    "l_midpoint_2_of_antihelix",
    "l_midpoint_3_of_antihelix",
    "l_point_1_of_inner_helix",
    "l_point_2_of_inner_helix",
    "l_point_3_of_inner_helix",
    "l_point_4_of_inner_helix",
    "l_point_5_of_inner_helix",
    "l_point_6_of_inner_helix",
    "l_point_7_of_inner_helix",
    "l_highest_point_of_antitragus",
    "l_bottom_point_of_tragus",
    "l_protruding_point_of_tragus",
    "l_top_point_of_tragus",
    "l_start_point_of_crus_of_helix",
    "l_deepest_point_of_concha",
    "l_tip_of_ear_lobe",
    "l_midpoint_between_22_15",
    "l_bottom_connecting_point_of_ear_lobe",
    "l_top_connecting_point_of_helix",
    "l_point_8_of_inner_helix",
    "r_top_end_of_inferior_crus",
    "r_top_end_of_superior_crus",
    "r_start_of_antihelix",
    "r_end_of_antihelix",
    "r_midpoint_1_of_antihelix",
    "r_midpoint_1_of_inferior_crus",
    "r_midpoint_2_of_antihelix",
    "r_midpoint_3_of_antihelix",
    "r_point_1_of_inner_helix",
    "r_point_8_of_inner_helix",
    "r_point_3_of_inner_helix",
    "r_point_4_of_inner_helix",
    "r_point_5_of_inner_helix",
    "r_point_6_of_inner_helix",
    "r_point_7_of_inner_helix",
    "r_highest_point_of_antitragus",
    "r_bottom_point_of_tragus",
    "r_protruding_point_of_tragus",
    "r_top_point_of_tragus",
    "r_start_point_of_crus_of_helix",
    "r_deepest_point_of_concha",
    "r_tip_of_ear_lobe",
    "r_midpoint_between_22_15",
    "r_bottom_connecting_point_of_ear_lobe",
    "r_top_connecting_point_of_helix",
    "r_point_2_of_inner_helix",
    "l_center_of_iris",
    "l_border_of_iris_3",
    "l_border_of_iris_midpoint_1",
    "l_border_of_iris_12",
    "l_border_of_iris_midpoint_4",
    "l_border_of_iris_9",
    "l_border_of_iris_midpoint_3",
    "l_border_of_iris_6",
    "l_border_of_iris_midpoint_2",
    "r_center_of_iris",
    "r_border_of_iris_3",
    "r_border_of_iris_midpoint_1",
    "r_border_of_iris_12",
    "r_border_of_iris_midpoint_4",
    "r_border_of_iris_9",
    "r_border_of_iris_midpoint_3",
    "r_border_of_iris_6",
    "r_border_of_iris_midpoint_2",
    "l_center_of_pupil",
    "l_border_of_pupil_3",
    "l_border_of_pupil_midpoint_1",
    "l_border_of_pupil_12",
    "l_border_of_pupil_midpoint_4",
    "l_border_of_pupil_9",
    "l_border_of_pupil_midpoint_3",
    "l_border_of_pupil_6",
    "l_border_of_pupil_midpoint_2",
    "r_center_of_pupil",
    "r_border_of_pupil_3",
    "r_border_of_pupil_midpoint_1",
    "r_border_of_pupil_12",
    "r_border_of_pupil_midpoint_4",
    "r_border_of_pupil_9",
    "r_border_of_pupil_midpoint_3",
    "r_border_of_pupil_6",
    "r_border_of_pupil_midpoint_2",
]
